### ISSUE TITLE
The reference documentation is unavailable

### ISSUE THREAD

**Issue by Fohlen** [libsigcplusplus/libsigcplusplus#13]
Unfortunately the [reference documentation](https://developer.gnome.org/libsigc++/stable/) has no content. This might be because (pressumably) the `github.io` presence of this library does still link back to the GNOME site. It would be amazing if this could be fixed 👍

**Comment by kjellahl** [comment]
The reference documentation at developer.gnome.org is empty, because the documentation
in the tarball has been generated by a fairly new version of Doxygen. This is an
annoying issue that affects not just libsigc++. Other affected modules are glibmm
and gtkmm. It has been known for more than a year.
See https://gitlab.gnome.org/Infrastructure/library-web/issues/12

**Comment by Fohlen** [comment]
@kjellahl and @murraycu what are the chances for moving documentation for `libsigc++` to GitHub pages? Would you like me to create a PR?

**Comment by murraycu** [comment]
@Fohlen That would be good, if possible. Thanks.

**Comment by kjellahl** [comment]
I have released 2.10.2 (stable) and 2.99.13 (unstable) with documentation generated
by Doxygen 1.8.11. The documentation is shown at https://developer.gnome.org/libsigc++

Shall this issue be closed?

**Comment by murraycu** [comment]
Thanks, Kjell.
