### ISSUE TITLE
Compile in Windows with VS2017 projects

### ISSUE THREAD

**Issue by fmoyaarnao** [libsigcplusplus/libsigcplusplus#2]
I'm trying to compile in Windows 10 with Visual Studio 2017 and I'm getting the next errors:

> 1>------ Rebuild All started: Project: sigc, Configuration: Debug Win32 ------
1>slot_base.cc
1>c:\workspace\libsigcplusplus\sigc++\functors\slot_base.cc : fatal error C1083: Cannot open include file: 'msvc_recommended_pragmas.h': No such file or directory
1>trackable.cc
1>c:\workspace\libsigcplusplus\sigc++\trackable.cc : fatal error C1083: Cannot open include file: 'msvc_recommended_pragmas.h': No such file or directory
1>signal_base.cc
1>c:\workspace\libsigcplusplus\sigc++\signal_base.cc : fatal error C1083: Cannot open include file: 'msvc_recommended_pragmas.h': No such file or directory
1>connection.cc
1>c:\workspace\libsigcplusplus\sigc++\connection.cc : fatal error C1083: Cannot open include file: 'msvc_recommended_pragmas.h': No such file or directory
1>Generating Code...
1>Done building project "libsigc++3.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by fanc999** [comment]
Hi @fmoyaarnao,

Hmm, the project files assumed that you have GLib installed, as libsigc++ is normally used with glibmm and gtkmm, but libsigc++ does not, on its own, depend on GLib directly...

What you can do for the time being:
-Get a GLib release tarball and use the msvc_recommended_pragmas.h in there.
-Edit the project properties so that it will not try to include msvc_recommended_pragmas.h, as it is force-included.

I am also making the project files into a set of NMake Makefiles (which also removed this requirement).

Hope this helps.

With blessings, and cheers!

**Comment by kjellahl** [comment]
@fanc999 Has this issue been fixed by your NMake files?

**Comment by fanc999** [comment]
Hi @kjellahl,,

Yes, this issue should be resolved at this point.  Sorry, I forgot to come back to this issue.

With blessings, thank you

**Comment by kjellahl** [comment]
Okay, then I close the issue.
