### ISSUE TITLE
How shall a committer act to failed CI checks?

### ISSUE THREAD

**Issue by kjellahl** [libsigcplusplus/libsigcplusplus#54]
The CI checks, performed after a commit is pushed, has a tendency to fail, both in libsigc++
and in other packages (jhbuild, gnome-build-meta). The failures often seem to have
no connection to the pushed commit. Example:

Commit https://github.com/libsigcplusplus/libsigcplusplus/commit/8c87c4b2ae3c002fbb799b731feef97ae84828fc
made changes in the meson.build files. The clang-9 test, which builds with autotools, failed with the result:

http://docbook.sourceforge.net/release/xsl/current/html/toc.xsl:1: parser error : Document is empty

All the other tests passed.

What is a committer supposed to do in such cases? If you just look at the list of
recent commits, it looks like this commit has introduced a bug. If you dig deeper
into the test results, it's not at all clear that the commit is the culprit.

Is there a reasonably easy way to repeat the CI checks without making a new push?

**Comment by murraycu** [comment]
In this case it's probably something about the environment used in the clang-9 CI build, not clang-9 itself.

However, generally:

There should be a way to retrigger builds that have failed for some infrastructure reason, or because they are not written to behave consistently. I'm not sure if there is - but that's a general GitHub question.

If CI builds are consistenly failing, and they can't be fixed, and they are not useful, they should be disabled.

Also, I guess that maintainers can override failing CI tests and commit ot master anyway, but it's not ideal to just do that, because then all future commits will fail too.

**Comment by kjellahl** [comment]
Fine that you found a "re-run jobs" button. I guess you also pressed it. Now all
CI tests have succeeded.
