### ISSUE TITLE
are there some other way to complile it in windows

### ISSUE THREAD

**Issue by babyaaaaaa** [libsigcplusplus/libsigcplusplus#61]
because i failed complile it with vs2019,  are there some other way to complile it in windows

**Comment by fanc999** [comment]
Hi @babyaaaaaa,

The best way is to wait for the next release of 3.x (which I believe is the version that you were trying to build).  If you really need to build it in a hurry, take a look at [1].

Oh, I think it will be best for questions that closely relate to a previously-closed issue, it would be best to continue asking questions in that issue instead of opening a new one, since it won't speed up a new release.

Closing this issue.

Thanks!

[1]: https://github.com/libsigcplusplus/libsigcplusplus/commit/a95f3ba07bba3e482c7340b332445a0ef38c1196
