### ISSUE TITLE
Issue with include folder when using msvc project instead of cmake

### ISSUE THREAD

**Issue by JackBoosY** [libsigcplusplus/libsigcplusplus#75]
Hi guys,
I'm vcpkg maintainer.
Recently we received an issue about the include path (https://github.com/microsoft/vcpkg/issues/21496).
We now know that libsigcpp will export the include path _include/sigc++-3.0_ to `sigc++-3Targets.cmake` that we need to add to the include path, but we may encounter some problems using Visual Studio directly.

When using Visual Studio, we must add three paths:
1. _include_
2. _include/sigc++-3.0_
3. _lib/include/sigc++-3.0_

This will make users feel very complicated.
Adding a layer of directory _sigc++-3.0_ will undoubtedly cause the above consequences.

What do you guys think?

**Comment by fanc999** [comment]
Hi,

I am not in the position to decide to whether to make this kind of change, since this is the way how things went for libsigc++ for a very long time.

To make things easier for usage directly in Visual Studio projects, I think the best bet is to make use of property sheets so that one can set up the include paths easier for the configs in the various projects that will make use of libsigc++.  Similarly, if one is also using items like gtkmm directly in Visual Studio projects, this is also what I would recommend as well.

With blessings, and cheers!

**Comment by kjellahl** [comment]
In Linux, 2 include paths are necessary for sigc++3.0:

- $PREFIX/include/sigc++-3.0
- $PREFIX/lib/sigc++-3.0/include

where $PREFIX is a common prefix for the include paths, such as /usr.
For sigc++-2.0, make the obvious replacement 3 -> 2.

Similar include paths are used for many other modules, with sigc++-3.0 replaced
by the names of those modules. This way of installing header files and giving
include paths to the compiler has been used for many years.

**Comment by JackBoosY** [comment]
Okay, we need to do some "localization" adaptation.
