### ISSUE TITLE
CI: Building with meson and MSVC

### ISSUE THREAD

**Issue by kjellahl** [libsigcplusplus/libsigcplusplus#98]
@fanc999-1 I've experimented with a CI test that builds libsigcplusplus
with meson and MSVC. It would be fine if you could have a look at it,
and suggest improvements.
See branch kjellahl/ci-meson-msvc, file .github/workflows/meson-msvc.yml.

I've copied a similar CI file from libxmlplusplus, and made some modifications.
It does not build the documentation. Is that possible?

**Comment by fanc999-1** [comment]
Hi @kjellahl,

Sorry for the delay, I think the CI config looks good to me, albeit I am by no means a CI config expert.

If I understood you correctly, to build the documentation would be much more complex, as installing GraphViz would be the most tedious unless one can grab its binaries to unpack, as one needs to be able to build and/or install libtool using Visual Studio (which requires a special setup) in order to build it (it's a major pain; GraphViz's CMake files have certain assumptions involved).  DoxyGen is easier, but will likely depend on LLVM support for our use case.

I think we would be fine for our case to just skip building documentation for Windows-MSVC CI.

With blessings, and cheers!

**Comment by kjellahl** [comment]
> Sorry for the delay

No reason to apologize for a 2-day delay. This is no urgent issue.

> I am by no means a CI config expert.

Neither am I.

I noticed in connection with PR #97 that it's good to have a CI test
that builds with MSVC (cmake-msvc.yml). It can find errors that only
show up with MSVC. I haven't got MSVC installed on a computer of my own.
But Meson is the recommended build system, so it's more important that
the build works with Meson than that it works with CMake or Autotools.

I noticed recently that it's possible to build the documentation with
Doxygen even if the `dot` command from GraphViz is not available.
It requires changes in Doxyfile.in and two meson.build files.
I've managed to build the reference documentation, but not the manual,
with MSVC. It also required a small fix in mm-common, to make it possible
to build mm-common as a subproject with the software that 
bus1/cabuild/action/msdevshell@v1 installs.

I will probably skip building the documentation when I add this CI test
to the master branch.
